### ISSUE TITLE
I am not able to install pointnet2_ops==3.0.0 in requirement.txt. Did you used PointNet in you implementations

### ISSUE THREAD

**Issue by mujtabaasad** [CVLAB-Unibo/crossmodal-feature-mapping#1]
I am using the following pytorch implementation of pointnet. However, I am not able to install it. https://github.com/erikwijmans/Pointnet2_PyTorch
How did you get it installed.

by the way did you used PointNet in the implementations?? as you mentioned PointMAE for pointcloud feature extraction

**Comment by zhiqing0205** [comment]
To resolve this issue, follow these steps:

1. Ensure your CUDA version is between 11.3 and 11.8.
2. Install the PyTorch version that matches your CUDA version.
3. Perform an offline installation:
```
git clone https://github.com/erikwijmans/Pointnet2_PyTorch.git
cd Pointnet2_PyTorch/pointnet2_ops_lib
pip install .
```

If you still encounter errors, it's likely due to your GCC version. Adjust the GCC version based on the specific error messages you receive.

**Comment by alex-costanzino** [comment]
Thanks @zhiqing0205 for reply!

**Comment by limaodaxia** [comment]
> To resolve this issue, follow these steps:
> 
> 1. Ensure your CUDA version is between 11.3 and 11.8.
> 2. Install the PyTorch version that matches your CUDA version.
> 3. Perform an offline installation:
> 
> ```
> git clone https://github.com/erikwijmans/Pointnet2_PyTorch.git
> cd Pointnet2_PyTorch/pointnet2_ops_lib
> pip install .
> ```
> 
> If you still encounter errors, it's likely due to your GCC version. Adjust the GCC version based on the specific error messages you receive.

thank you very much, I ran the model. But the result is about 93.7, which is worser than the results mentioned in the paper. What maybe the reason?

**Comment by alex-costanzino** [comment]
Hi @limaodaxia, have you pre-processed the dataset?
There were two other similar issues solved by pre-processing the dataset from scratch (https://github.com/CVLAB-Unibo/crossmodal-feature-mapping/issues/6 and https://github.com/CVLAB-Unibo/crossmodal-feature-mapping/issues/3).
