### ISSUE TITLE
 The results I reproduced are inconsistent with those in the paper. Are there any specific aspects I should pay attention to?

### ISSUE THREAD

**Issue by noobiotlxp** [CVLAB-Unibo/crossmodal-feature-mapping#3]
Thank you for your excellent work. I have successfully run your code, but why are the results different from those in the paper? For example, ![image](https://github.com/user-attachments/assets/c489417b-3add-403a-b08d-144fe2983d29). Looking forward to your reply.

**Comment by Looksing** [comment]
I'm encountering similar problem as you. How did you manage to solve it?

**Comment by gfever1** [comment]
So do I，
![image](https://github.com/user-attachments/assets/ee6a2f02-cbd4-4884-b781-d35464daa9af)
i really need help for this issue

**Comment by alex-costanzino** [comment]
I addressed this problem via e-mail, which is usually due to missing dataset preprocessing.
