### ISSUE TITLE
Why the model created by timm (if not load the pretrained weight) have different weight everytime？How to set the seed of timm?

### ISSUE THREAD

**Issue by limaodaxia** [CVLAB-Unibo/crossmodal-feature-mapping#4]
Why the model created by timm (if not load the pretrained weight) have different weight everytime？How to set the seed of timm?

**Comment by alex-costanzino** [comment]
For this work, we loaded the weights directly from the file. I think that to answer to this question it would be better to open an issue under the timm repo of this model.
