### ISSUE TITLE
where is "checkpoints/feature_extractors/pointmae_pretrain.pth"

### ISSUE THREAD

**Issue by qtewyhzd** [CVLAB-Unibo/crossmodal-feature-mapping#5]
Where is the checkpoints file located in this line of code?
Code: self.xyz_backbone.load_model_from_ckpt("checkpoints/feature_extractors/pointmae_pretrain.pth")[https://github.com/CVLAB-Unibo/crossmodal-feature-mapping/blob/main/models/full_models.py](url)

**Comment by alex-costanzino** [comment]
You can find it in the checkpoint section of the readme, there is a link to google drive.
