### ISSUE TITLE
we met  a error （[Open3D Error] ） when  we executed command of  "python  preprocess_mvtec" 

### ISSUE THREAD

**Issue by zhaoyuan1209** [CVLAB-Unibo/crossmodal-feature-mapping#7]
The detailed error is shown as follows:
RuntimeError: [Open3D Error] (std::tuple<Eigen::Matrix<double, 4, 1, 0, 4, 1>, std::vector<long unsigned int, std::allocator<long unsigned int> > > open3d::geometry::PointCloud::SegmentPlane(double, int, int, double) const) /root/Open3D/cpp/open3d/geometry/PointCloudSegmentation.cpp:175: There must be at least 'ransac_n' points.

**Comment by alex-costanzino** [comment]
It seems that there are not enough support points to compute the plane.
The problem could be either that:
* the dataset was already pre-processed;
* the path to the dataset is wrong or the format is not the one expected by the script.

**Comment by zhaoyuan1209** [comment]
Thanks, we have resolved the issue. The reason for the problem was that the dataset had already been pre-processed.
